version: '3.3'
services:
  postgres:
    image: postgres:16.2-alpine3.19
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ponzu 
    ports:
      - "5432:5432"
    container_name: ponzu 
